In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothic'


import os, sys, random
from pathlib import Path
import glob

from tqdm import tqdm
from fastprogress import progress_bar

import warnings
warnings.filterwarnings(action='ignore')

CUR_DIR = Path.cwd()
DATA_DIR = CUR_DIR / 'data/preprocessed'
DATA_DIR

WindowsPath('C:/Users/안현준/풍년보험/data/preprocessed')

In [2]:
crops = ['감자', '고구마', '고추(화건)', '깻잎', '녹두(국산)', '단감', '당근(무세척)', '대파', '들깨(국산)',
       '딸기', '무', '미나리', '방울토마토', '배(신고)', '배추', '백참깨(국산)', '복숭아(백도)',
       '사과(후지)', '생강(국산)', '수박', '시금치', '애호박', '양배추', '양파', '오이(가시)', '적상추',
       '참외', '콩(흰콩국산)', '토마토', '팥(국산)', '포도(캠벨)', '풋고추']
TARGET_YEAR = [2017, 2018, 2019, 2020]

In [4]:
for crop in crops:
    df = pd.read_csv(f'./results/{crop}/premiums_{crop}.csv')
    break
df

,year,감자_true,감자_pred,MA_5_true,MA_5_pred,보험지급여부_true,보험지급여부_pred,빈도_mean_true,빈도_mean_pred,심도_true,심도_pred,심도_mean_true,심도_mean_pred,보험료_true
0,2006,17184.834000,17066.737958,20178.283517,21331.267400,1,1,1.000000,1.000000,2993.449517,4264.529442,2993.449517,4264.529442,2993.449517
1,2007,20779.584083,23665.073583,20877.116850,21410.781592,1,0,1.000000,0.500000,97.532767,0.000000,1545.491142,2132.264721,1545.491142
2,2008,25183.499833,27049.700583,22099.566917,22643.843392,0,0,0.666667,0.333333,0.000000,0.000000,1030.327428,1421.509814,686.884952
3,2009,26209.417167,26372.851667,22760.766867,23863.047892,0,0,0.500000,0.250000,0.000000,0.000000,772.745571,1066.132360,386.372785
4,2010,31893.082667,29762.191000,21599.300333,23307.070558,0,0,0.400000,0.200000,0.000000,0.000000,618.196457,852.905888,247.278583
5,2011,33519.000167,30357.644083,24250.083550,24783.310958,0,0,0.333333,0.166667,0.000000,0.000000,515.163714,710.754907,171.721238
6,2012,35677.082667,30917.449667,27516.916783,27441.492183,0,0,0.285714,0.142857,0.000000,0.000000,441.568898,609.218492,126.162542
7,2013,24260.999667,26489.236167,30496.416500,28891.967400,1,1,0.375000,0.250000,6235.416833,2402.731233,1165.799890,833.407584,437.174959
8,2014,22752.416833,25430.168500,30311.916467,28779.874517,1,1,0.444444,0.333333,7559.499633,3349.706017,1876.210972,1112.996299,833.871543
9,2015,32442.999833,28822.863417,29620.516400,28591.337883,0,0,0.400000,0.300000,0.000000,0.000000,1688.589875,1001.696669,675.435950
10,2016,28445.416167,28354.866083,29730.499833,28403.472367,1,1,0.454545,0.363636,1285.083667,48.606283,1651.907492,915.052089,750.867042
11,2017,40058.083667,32636.257917,28715.783033,28002.916767,0,0,0.416667,0.333333,0.000000,0.000000,1514.248535,838.797748,630.936889
12,2018,52831.250000,29911.632333,29591.983233,28346.678417,0,0,0.384615,0.307692,0.000000,0.000000,1397.767878,774.274844,537.603030
13,2019,32584.417333,26479.361750,35306.033300,29031.157650,1,1,0.428571,0.357143,2721.615967,2551.795900,1492.328456,901.240634,639.569338
14,2020,31512.250500,29596.628417,37272.433400,29240.996300,1,0,0.466667,0.333333,5760.182900,0.000000,1776.852086,841.157925,829.197640